/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiStreamJobIdRouteImport } from './routes/api/stream.$jobId'
import { Route as ApiModelJobIdRouteImport } from './routes/api/model.$jobId'
import { Route as ApiMeshJobIdRouteImport } from './routes/api/mesh.$jobId'
import { Route as ApiCompanionJobIdRouteImport } from './routes/api/companion.$jobId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamJobIdRoute = ApiStreamJobIdRouteImport.update({
  id: '/api/stream/$jobId',
  path: '/api/stream/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelJobIdRoute = ApiModelJobIdRouteImport.update({
  id: '/api/model/$jobId',
  path: '/api/model/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshJobIdRoute = ApiMeshJobIdRouteImport.update({
  id: '/api/mesh/$jobId',
  path: '/api/mesh/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionJobIdRoute = ApiCompanionJobIdRouteImport.update({
  id: '/api/companion/$jobId',
  path: '/api/companion/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/companion/$jobId': typeof ApiCompanionJobIdRoute
  '/api/mesh/$jobId': typeof ApiMeshJobIdRoute
  '/api/model/$jobId': typeof ApiModelJobIdRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/companion/$jobId': typeof ApiCompanionJobIdRoute
  '/api/mesh/$jobId': typeof ApiMeshJobIdRoute
  '/api/model/$jobId': typeof ApiModelJobIdRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/companion/$jobId': typeof ApiCompanionJobIdRoute
  '/api/mesh/$jobId': typeof ApiMeshJobIdRoute
  '/api/model/$jobId': typeof ApiModelJobIdRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/upload'
    | '/api/companion/$jobId'
    | '/api/mesh/$jobId'
    | '/api/model/$jobId'
    | '/api/stream/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/upload'
    | '/api/companion/$jobId'
    | '/api/mesh/$jobId'
    | '/api/model/$jobId'
    | '/api/stream/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/upload'
    | '/api/companion/$jobId'
    | '/api/mesh/$jobId'
    | '/api/model/$jobId'
    | '/api/stream/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiCompanionJobIdRoute: typeof ApiCompanionJobIdRoute
  ApiMeshJobIdRoute: typeof ApiMeshJobIdRoute
  ApiModelJobIdRoute: typeof ApiModelJobIdRoute
  ApiStreamJobIdRoute: typeof ApiStreamJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$jobId': {
      id: '/api/stream/$jobId'
      path: '/api/stream/$jobId'
      fullPath: '/api/stream/$jobId'
      preLoaderRoute: typeof ApiStreamJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/$jobId': {
      id: '/api/model/$jobId'
      path: '/api/model/$jobId'
      fullPath: '/api/model/$jobId'
      preLoaderRoute: typeof ApiModelJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh/$jobId': {
      id: '/api/mesh/$jobId'
      path: '/api/mesh/$jobId'
      fullPath: '/api/mesh/$jobId'
      preLoaderRoute: typeof ApiMeshJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion/$jobId': {
      id: '/api/companion/$jobId'
      path: '/api/companion/$jobId'
      fullPath: '/api/companion/$jobId'
      preLoaderRoute: typeof ApiCompanionJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiCompanionJobIdRoute: ApiCompanionJobIdRoute,
  ApiMeshJobIdRoute: ApiMeshJobIdRoute,
  ApiModelJobIdRoute: ApiModelJobIdRoute,
  ApiStreamJobIdRoute: ApiStreamJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
